CREATE DATABASE telecom_churn;
USE telecom_churn;

CREATE TABLE telecom_churn_raw (
    customerID VARCHAR(50),
    gender VARCHAR(10),
    SeniorCitizen INT,
    Partner VARCHAR(5),
    Dependents VARCHAR(5),
    tenure INT,
    PhoneService VARCHAR(5),
    MultipleLines VARCHAR(30),
    InternetService VARCHAR(30),
    OnlineSecurity VARCHAR(30),
    OnlineBackup VARCHAR(30),
    DeviceProtection VARCHAR(30),
    TechSupport VARCHAR(30),
    StreamingTV VARCHAR(30),
    StreamingMovies VARCHAR(30),
    Contract VARCHAR(30),
    PaperlessBilling VARCHAR(5),
    PaymentMethod VARCHAR(50),
    MonthlyCharges DECIMAL(10,2),
    TotalCharges DECIMAL(10,2),
    Churn VARCHAR(5)
);


-- Customers table
CREATE TABLE customers (
    customerID VARCHAR(50) PRIMARY KEY,
    gender VARCHAR(10),
    SeniorCitizen INT,
    Partner VARCHAR(5),
    Dependents VARCHAR(5),
    tenure INT
);

-- Services Table
CREATE TABLE services (
    customerID VARCHAR(50),
    PhoneService VARCHAR(5),
    MultipleLines VARCHAR(30),
    InternetService VARCHAR(30),
    OnlineSecurity VARCHAR(30),
    OnlineBackup VARCHAR(30),
    DeviceProtection VARCHAR(30),
    TechSupport VARCHAR(30),
    StreamingTV VARCHAR(30),
    StreamingMovies VARCHAR(30),
    CONSTRAINT fk_services_customer
        FOREIGN KEY (customerID) REFERENCES customers(customerID)
);

-- Billing Table
CREATE TABLE billing (
    customerID VARCHAR(50),
    Contract VARCHAR(30),
    PaperlessBilling VARCHAR(5),
    PaymentMethod VARCHAR(50),
    MonthlyCharges DECIMAL(10,2),
    TotalCharges DECIMAL(10,2),
    Churn VARCHAR(5),
    CONSTRAINT fk_billing_customer
        FOREIGN KEY (customerID) REFERENCES customers(customerID)
);


INSERT INTO customers
SELECT DISTINCT
customerID, gender, SeniorCitizen, Partner, Dependents, tenure
FROM telecom_churn_raw;

INSERT INTO services
SELECT DISTINCT
customerID, PhoneService, MultipleLines, InternetService,
OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport,
StreamingTV, StreamingMovies
FROM telecom_churn_raw;

INSERT INTO billing
SELECT DISTINCT
customerID, Contract, PaperlessBilling, PaymentMethod,
MonthlyCharges, TotalCharges, Churn
FROM telecom_churn_raw;

SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM services;
SELECT COUNT(*) FROM billing;

-- 1. What is the total number of customers present in the telecom dataset?
SELECT COUNT(*) AS total_customers
FROM customers;

-- 2. What is the total number of customers who have discontinued the service?
SELECT COUNT(*) AS churned_customers
FROM billing
WHERE Churn = 'Yes';

-- 3. What percentage of the total customer base has churned?
SELECT
ROUND(SUM(Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate_percentage
FROM billing;

-- 4. How does customer churn behavior vary across different genders?
SELECT 
c.gender,
COUNT(*) AS total_customers,
SUM(b.Churn = 'Yes') AS churned,
ROUND(SUM(b.Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate
FROM customers c
JOIN billing b ON c.customerID = b.customerID
GROUP BY c.gender;

-- 5.What impact does senior citizen status have on customer churn?
SELECT 
c.SeniorCitizen,
COUNT(*) AS total_customers,
SUM(b.Churn = 'Yes') AS churned,
ROUND(SUM(b.Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate
FROM customers c
JOIN billing b ON c.customerID = b.customerID
GROUP BY c.SeniorCitizen;

-- 6.How does customer churn differ across various contract types?
SELECT 
b.Contract,
COUNT(*) AS total_customers,
SUM(b.Churn = 'Yes') AS churned,
ROUND(SUM(b.Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate
FROM billing b
GROUP BY b.Contract;

-- 7.What is the relationship between internet service type and customer churn?
SELECT 
s.InternetService,
COUNT(*) AS total_customers,
SUM(b.Churn = 'Yes') AS churned,
ROUND(SUM(b.Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate
FROM services s
JOIN billing b ON s.customerID = b.customerID
GROUP BY s.InternetService;

-- 8.How does customer tenure differ between churned and retained customers?
SELECT 
b.Churn,
AVG(c.tenure) AS avg_tenure
FROM customers c
JOIN billing b ON c.customerID = b.customerID
GROUP BY b.Churn;

-- 9.What differences exist in average monthly charges between churned and non-churned customers?
SELECT 
b.Churn,
AVG(b.MonthlyCharges) AS avg_monthly_charges
FROM billing b
GROUP BY b.Churn;

-- 10.What is the total revenue generated by the telecom company?
SELECT SUM(TotalCharges) AS total_revenue
FROM billing;

-- 11.What is the total revenue loss attributed to customer churn?
SELECT SUM(TotalCharges) AS revenue_lost
FROM billing
WHERE Churn = 'Yes';

-- 12.How is revenue distributed across different contract categories?
SELECT 
Contract,
SUM(TotalCharges) AS total_revenue
FROM billing
GROUP BY Contract
ORDER BY total_revenue DESC;

-- 13.How can customers be ranked based on their lifetime revenue contribution?
SELECT 
customerID,
TotalCharges,
RANK() OVER (ORDER BY TotalCharges DESC) AS revenue_rank
FROM billing;

-- 14.Who are the top-performing customers in terms of total revenue generated?
SELECT 
customerID,
TotalCharges
FROM billing
ORDER BY TotalCharges DESC
LIMIT 10;

-- 15.How can customers be classified into risk segments based on churn status and revenue contribution?
SELECT 
c.customerID,
CASE
    WHEN b.Churn = 'Yes' AND b.TotalCharges > 3000 THEN 'High Value – High Risk'
    WHEN b.Churn = 'No'  AND b.TotalCharges > 3000 THEN 'High Value – Low Risk'
    ELSE 'Low Value'
END AS customer_segment
FROM customers c
JOIN billing b ON c.customerID = b.customerID;

-- 16.How does customer churn vary across different customer tenure segments?
SELECT
b.PaymentMethod,
COUNT(*) AS total_customers,
SUM(b.Churn = 'Yes') AS churned,
ROUND(SUM(b.Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate
FROM billing b
GROUP BY b.PaymentMethod
ORDER BY churn_rate DESC;

-- 17.How does customer churn behavior change across different monthly billing ranges?
SELECT
CASE
    WHEN b.MonthlyCharges < 50 THEN 'Low Charges'
    WHEN b.MonthlyCharges BETWEEN 50 AND 80 THEN 'Medium Charges'
    ELSE 'High Charges'
END AS charge_group,
COUNT(*) AS total_customers,
SUM(b.Churn = 'Yes') AS churned,
ROUND(SUM(b.Churn = 'Yes') * 100.0 / COUNT(*), 2) AS churn_rate
FROM billing b
GROUP BY charge_group
ORDER BY churn_rate DESC;

